export const carslist = [
  {
    brand: 'Audi',
    model: 'RS 5 Coupé',
    labelPrice: 'Ao dia',
    price: 'R$ 120',
    fuelType: 'electric',
    source: require('../assets/Audi.png'),
  },
  {
    brand: 'Porche',
    model: 'Panamera',
    labelPrice: 'Ao dia',
    price: 'R$ 340',
    fuelType: 'gas',
    source: require('../assets/Porche.png'),
  },
  {
    brand: 'Chevrolet',
    model: 'Corvette Z06',
    labelPrice: 'Ao dia',
    price: 'R$ 620',
    fuelType: 'gas',
    source: require('../assets/Corvete.png'),
  },
  {
    brand: 'Lamborghini',
    model: 'Huracan',
    labelPrice: 'Ao dia',
    price: 'R$ 120',
    fuelType: 'electric',
    source: require('../assets/Lambo.png'),
  },
  {
    brand: 'Volvo',
    model: 'XC40',
    labelPrice: 'Ao dia',
    price: 'R$ 260',
    fuelType: 'gas',
    source: require('../assets/Volvo.png'),
  },
  {
    brand: 'Mitsubishi',
    model: 'Lancer Evo X',
    labelPrice: 'Ao dia',
    price: 'R$ 290',
    fuelType: 'gas',
    source: require('../assets/Lancer.png'),
  },
];
